import { getInfo } from "../../../server-funcs/fetch-info";

export default async function AnotherLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { name: string };
}) {
  const pokeProfile = await getInfo("bulbasaur");

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div
          style={{
            width: "100vw",
            height: "100vh",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <div
            style={{ height: "20px", backgroundColor: "pink", width: "100vw" }}
          >
            Hi {pokeProfile.name}!
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
