import { getPokemonByName } from "@/server/fetch-info";

export default async function AnotherLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { name: string };
}) {
  const pokeProfile = await getPokemonByName(params.name);

  return (
    <>
      <head>
        <title>{params.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div className="w-screen h-screen flex flex-col">
        <div className="mx-4 py-2 border-b-2">
          <div className="text-xl font-bold">Pokedexicon</div>
        </div>
        <div className="p-4">{children}</div>
      </div>
    </>
  );
}
